version: "3.9"

services:
  db:
    image: postgres:15
    container_name: livs_db
    environment:
      POSTGRES_USER: livs
      POSTGRES_PASSWORD: livs_pass
      POSTGRES_DB: livs_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: